rvm:
  - 1.9.3
  - 2.0.0
  # - rbx-2.0
  # - jruby

env:
  - GEM=sunspot
  - GEM=sunspot_rails RAILS=3.0.0
  - GEM=sunspot_rails RAILS=3.1.0
  - GEM=sunspot_rails RAILS=3.2.0

# Limit the size of the matrix by only performing the most common builds
matrix:
  exclude:
    # Not supporting Ruby 2.0 and Rails < 3.2
    - rvm: 2.0.0
      env: GEM=sunspot_rails RAILS=3.0.0
    - rvm: 2.0.0
      env: GEM=sunspot_rails RAILS=3.1.0

script:
  - ci/travis.sh
